In [1]:
from hmmlearn import hmm
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from hmmlearn import hmm

In [2]:
base_dir = "https://github.com/natsunoyuki/Data_Science/blob/master/gold/gold/gold_price_usd.csv?raw=True"

data = pd.read_csv(base_dir)

# Convert the datetime from str to datetime object.
data["datetime"] = pd.to_datetime(data["datetime"])

# Determine the daily change in gold price.
data["gold_price_change"] = data["gold_price_usd"].diff()

In [4]:
# Restrict the data to later than 2008 Jan 01.
data = data[data["datetime"] >= pd.to_datetime("2008-01-01")]
X = data[["gold_price_change"]].values

model = hmm.GaussianHMM(n_components = 3, covariance_type = "diag", n_iter = 50, random_state = 42)
model.fit(X)

Z = model.predict(X)
states = pd.unique(Z)

In [5]:
print("Unique states:")
print(states)


Unique states:
[1 0 2]


In [6]:
print("\nStart probabilities:")
print(model.startprob_)


Start probabilities:
[9.00876474e-03 9.90991235e-01 1.90652535e-52]


In [7]:
print(model.transmat_)

[[4.71987506e-02 9.52205396e-01 5.95853639e-04]
 [8.12868067e-01 1.35345228e-01 5.17867054e-02]
 [3.95757463e-02 4.27802116e-02 9.17644042e-01]]


In [8]:
print(model.means_)

[[0.27897404]
 [0.20658205]
 [0.30620104]]


In [9]:
print(model.covars_)

[[[ 28.11246244]]

 [[ 77.18151421]]

 [[324.43713708]]]
