In [1]:
from pydataset import data
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split as tts

In [2]:
data = data('iris')
data.head(5)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           5.1          3.5           1.4          0.2  setosa
2           4.9          3.0           1.4          0.2  setosa
3           4.7          3.2           1.3          0.2  setosa
4           4.6          3.1           1.5          0.2  setosa
5           5.0          3.6           1.4          0.2  setosa

In [9]:
data['Species'].replace(['setosa','virginica','versicolor'],[0,1,2],inplace=True)
data.head(5)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
1           5.1          3.5           1.4          0.2        0
2           4.9          3.0           1.4          0.2        0
3           4.7          3.2           1.3          0.2        0
4           4.6          3.1           1.5          0.2        0
5           5.0          3.6           1.4          0.2        0

In [10]:
X = data.iloc[:,0:4]
y = data.iloc[:,4].values
X_train,X_test,y_train,y_test = tts(X,y,test_size=0.15,random_state=0)


In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [13]:
clf = LogisticRegression()
clf.fit(X_train,y_train)
clf.score(X_train,y_train)

0.9606299212598425

In [14]:
y_pred = clf.predict(X_test)
y_pred

array([1, 2, 0, 1, 0, 1, 0, 2, 2, 2, 1, 2, 2, 2, 2, 0, 2, 2, 0, 0, 1, 2,
       0], dtype=int64)

In [15]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[ 7  0  0]
 [ 0  5  0]
 [ 0  0 11]]
